export const astrologers = [
  {
    id: 1,
    name: "Priya Sharma",
    experience: "12+ years",
    specialization: "Vedic Astrology & Palmistry",
    rating: 4.9,
    reviews: 1247,
    expertise: [
      "Career Guidance",
      "Relationship Compatibility",
      "Financial Planning",
      "Marriage Prospects",
    ],
    languages: ["Hindi", "English", "Punjabi"],
    image: "/astrologers/priya-sharma.jpg",
    whatsappNumber: "+919876543210",
    about:
      "Renowned Vedic astrologer with 12+ years of experience in helping people find their true path through ancient astrological principles. Specialized in career guidance and relationship compatibility.",
    successRate: "95%",
    clientsHelped: "5000+",
    consultationFee: "₹799",
    responseTime: "Within 15 minutes",
    availability: "24/7",
    skills: [
      "Kundli Analysis",
      "Muhurta",
      "Gemstone Recommendation",
      "Vastu Shastra",
    ],
  },
  {
    id: 2,
    name: "Rajesh Kumar",
    experience: "15+ years",
    specialization: "Numerology & KP Astrology",
    rating: 4.8,
    reviews: 892,
    expertise: [
      "Marriage Compatibility",
      "Business Growth",
      "Health Issues",
      "Legal Matters",
    ],
    languages: ["Hindi", "Tamil", "English", "Telugu"],
    image: "/astrologers/rajesh-kumar.jpg",
    whatsappNumber: "+919876543211",
    about:
      "Expert in numerology and KP astrology system, specializing in accurate predictions and practical solutions for life challenges. Known for precise business and marriage predictions.",
    successRate: "92%",
    clientsHelped: "4200+",
    consultationFee: "₹699",
    responseTime: "Within 20 minutes",
    availability: "24/7",
    skills: ["Numerology", "KP System", "Horary Astrology", "Remedial Measures"],
  },
  {
    id: 3,
    name: "Anita Desai",
    experience: "8+ years",
    specialization: "Tarot Reading & Crystal Healing",
    rating: 4.7,
    reviews: 567,
    expertise: [
      "Love Problems",
      "Spiritual Growth",
      "Career Transition",
      "Personal Development",
    ],
    languages: ["English", "Marathi", "Hindi", "Gujarati"],
    image: "/astrologers/anita-desai.jpg",
    whatsappNumber: "+919876543212",
    about:
      "Combining tarot wisdom with crystal healing to provide holistic guidance and transformative solutions for modern life challenges. Special focus on spiritual and personal growth.",
    successRate: "90%",
    clientsHelped: "3000+",
    consultationFee: "₹899",
    responseTime: "Within 10 minutes",
    availability: "24/7",
    skills: ["Tarot Reading", "Crystal Healing", "Meditation Guidance", "Energy Healing"],
  },
  {
    id: 4,
    name: "Dr. Vikram Singh",
    experience: "20+ years",
    specialization: "Medical Astrology & Prashna",
    rating: 4.9,
    reviews: 1563,
    expertise: [
      "Health Issues",
      "Medical Astrology",
      "Prashna Kundli",
      "Remedial Astrology",
    ],
    languages: ["Hindi", "English", "Sanskrit"],
    image: "/astrologers/vikram-singh.jpg",
    whatsappNumber: "+919876543213",
    about:
      "Doctorate in Vedic astrology with specialization in medical astrology and Prashna. Known for accurate health predictions and effective remedial solutions.",
    successRate: "96%",
    clientsHelped: "6800+",
    consultationFee: "₹999",
    responseTime: "Within 30 minutes",
    availability: "10 AM - 8 PM",
    skills: ["Medical Astrology", "Prashna", "Mantra Therapy", "Yagya Recommendations"],
  },
  {
    id: 5,
    name: "Meera Patel",
    experience: "10+ years",
    specialization: "Love & Relationship Astrology",
    rating: 4.8,
    reviews: 734,
    expertise: [
      "Love Marriage",
      "Relationship Issues",
      "Family Problems",
      "Divorce Guidance",
    ],
    languages: ["Hindi", "English", "Gujarati", "Marathi"],
    image: "/astrologers/meera-patel.jpg",
    whatsappNumber: "+919876543214",
    about:
      "Specialized in love and relationship astrology with proven track record of helping thousands find love and resolve relationship issues. Compassionate and understanding approach.",
    successRate: "94%",
    clientsHelped: "3500+",
    consultationFee: "₹749",
    responseTime: "Within 15 minutes",
    availability: "24/7",
    skills: [
      "Relationship Analysis",
      "Compatibility Matching",
      "Love Remedies",
      "Marriage Counseling",
    ],
  },
  {
    id: 6,
    name: "Arjun Mehta",
    experience: "7+ years",
    specialization: "Career & Business Astrology",
    rating: 4.7,
    reviews: 423,
    expertise: [
      "Career Growth",
      "Business Success",
      "Job Change",
      "Investment Guidance",
    ],
    languages: ["Hindi", "English", "Bengali"],
    image: "/astrologers/arjun-mehta.jpg",
    whatsappNumber: "+919876543215",
    about:
      "Young and dynamic astrologer specializing in career and business predictions. Known for practical advice and modern approach to traditional astrology.",
    successRate: "91%",
    clientsHelped: "2200+",
    consultationFee: "₹649",
    responseTime: "Within 10 minutes",
    availability: "24/7",
    skills: [
      "Career Prediction",
      "Business Horoscope",
      "Financial Astrology",
      "Remedial Solutions",
    ],
  },
];

export default astrologers;
